apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gecko-front-end
spec:
  replicas: 2
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      containers:
        - name: gecko-front-end
          image: gecko/frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 80
     